# Gauss-Seidel Iteration

A method that improves upon *Jacobi Iteration*

Basic principle:

It is obvious that we are computing elements in the solution vector $\vec{x}$ one by one. So, when calculating a component we can then utilize the $x$ 's that has already been calculated in this round of iterations instead of just using the solution obtained in the previous round of iterations

The iterative is given as:

$$
x_i^{(k+1)} = \frac{1}{a_{ii}} ( b_i - \sum_{j=1}^{i-1} a_{ij}\cdot x_j^{(k+1)} - \sum_{j=i+1}^n a_{ij}\cdot x_j^{(k)} )
$$

In [7]:
import numpy as np

def gs_iteration(A, b, x_0, epsilon):
    k = 1
    n = len(b)
    x_pre = x_0
    x_cur = np.zeros(n)
    
    while True:
        for i in range(n):
            if i == 0:
                x_cur[i] = (b[i] - np.sum(A[i, :] * x_pre[:]) + A[i, i] * x_pre[i]) / A[i, i]
            else:
                x_cur[i] = (b[i] - np.sum(A[i, :i] * x_cur[:i]) - np.sum(A[i, i+1:] * x_pre[i+1:])) / A[i, i]
        
        err = np.linalg.norm(x_cur - x_pre)
        x_pre = x_cur.copy()
        print(f"{k} iteration")
        k = k + 1
        print(x_cur)
        
        if err < epsilon:
            break
        
A = np.array([[5,-1,-1,-1],
              [-1,10,-1,-1],
              [-1,-1,5,-1],
              [-1,-1,-1,10],])
b = np.array([-4,12,8,34])
x_0 = np.zeros(4)

gs_iteration(A, b, x_0, 1e-4)
        

1 iteration
[-0.8     1.12    1.664   3.5984]
2 iteration
[0.47648    1.773888   2.7697536  3.90201216]
3 iteration
[0.88913075 1.95608965 2.94944651 3.97946669]
4 iteration
[0.97700057 1.99059138 2.98941173 3.99570037]
5 iteration
[0.99514069 1.99802528 2.99777327 3.99909392]
6 iteration
[0.99897849 1.99958457 2.9995314  3.99980945]
7 iteration
[0.99978508 1.99991259 2.99990142 3.99995991]
8 iteration
[0.99995479 1.99998161 2.99997926 3.99999157]
9 iteration
[0.99999049 1.99999613 2.99999564 3.99999823]
