# Jacobi Iteration

Basic principle:
$\textbf{A} \cdot \vec{x} = \vec{b} \rightarrow \vec{x} = \textbf{B} \cdot \vec{x} + \vec{d}$

given simultaneous linear equations/ a linear system:

$$
\begin{cases}
    a_{11} x_1 + a_{12} x_2 + ... + a_{1n} x_n = b_1 \\
    a_{21} x_1 + a_{22} x_2 + ... + a_{2n} x_n = b_2 \\
    ... \\
    a_{n1} x_1 + a_{n2} x_2 + ... + a_{nn} x_n = b_n
\end{cases}
$$

It can be converted to:

$$
\begin{cases}
    a_{11} x_1 = b_1 - (a_{12} x_2 + ... + a_{1n} x_n) \\
    a_{22} x_2 = b_2 - (a_{21} x_1 + ... + a_{2n} x_n) \\
    ... \\
    a_{nn} x_n = b_n - (a_{n1} x_1 + ... + a_{n-1 n} x_{n-1})
\end{cases}
$$

Step by step, we can get the iterative:

$$
x_{i}^{(k+1)} = \frac{1}{a_{ii}} \cdot (b_i - \sum_{j = 1, j \neq i}^{n} a_{ij} x_{j}^{(k)})
$$

In [1]:
import numpy as np

def jacobi_iteration(A, b, x_0, epsilon):
    k = 1
    n = len(b)
    x_pre = x_0
    x_cur = np.zeros(n)
    
    for i in range(n):
        x_cur[i] = (b[i] - np.sum(A[i, :] * x_pre[:n]) + A[i, i] * x_pre[i]) / A[i, i]
        
    err = np.linalg.norm(x_cur - x_pre)
    x_pre = x_cur.copy()
    print(f"{k} iteration")
    print(x_cur)
    
    while err >= epsilon:
        for i in range(n):
            x_cur[i] = (b[i] - np.sum(A[i, :] * x_pre[:n]) + A[i, i] * x_pre[i]) / A[i, i]
            
        err = np.linalg.norm(x_cur - x_pre)
        x_pre = x_cur.copy()
        k += 1
        print(f"{k} iteration")
        print(x_cur)


A = np.array([[5,-1,-1,-1],
              [-1,10,-1,-1],
              [-1,-1,5,-1],
              [-1,-1,-1,10],])
b = np.array([-4,12,8,34])
x_0 = np.zeros(4)

jacobi_iteration(A, b, x_0, 1e-4)

1 iteration
[-0.8  1.2  1.6  3.4]
2 iteration
[0.44 1.62 2.36 3.6 ]
3 iteration
[0.716 1.84  2.732 3.842]
4 iteration
[0.8828 1.929  2.8796 3.9288]
5 iteration
[0.94748 1.96912 2.94812 3.96914]
6 iteration
[0.977276 1.986474 2.977148 3.986472]
7 iteration
[0.9900188 1.9940896 2.9900444 3.9940898]
8 iteration
[0.99564476 1.9974153  2.99563964 3.99741528]
9 iteration
[0.99809404 1.99886997 2.99809507 3.99886997]
10 iteration
[0.999167   1.99950591 2.9991668  3.99950591]
11 iteration
[0.99963572 1.99978397 2.99963576 3.99978397]
12 iteration
[0.99984074 1.99990555 2.99984073 3.99990555]
13 iteration
[0.99993036 1.9999587  2.99993037 3.9999587 ]
14 iteration
[0.99996955 1.99998194 2.99996955 3.99998194]
